### ISSUE TITLE
Publish to NuGet.org

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Management#1]
Please prepare release for this module
- [x] Add logo
- [x] Add nuspec file
- [ ] Prepare nuspec file for release
  - [ ] version (proposal for version: `0.0.9`)
  - [ ] release notes (`* Initial release`)

TeamCity release job is ready and will be executed on GitFlow release

**Comment by dfch** [comment]
resolved c55f3c0
